title: SIR Lab Ecosystem
description: SIR Ecosystem Guides

# Urls
url: "https://sir-lab.github.io"
baseurl: "/Ecosystem"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.5.2
plugins:
  - jekyll-remote-theme

# Configurations
search_enabled: false
heading_anchors: true


# 指定源目录为 docs
source: docs

# 其他功能配置
back_to_top: true
back_to_top_text: "Back to top"

exclude:
  - CHANGELOG.md
  - MIGRATION.md
  - README.md
  - LICENSE
  - LICENSE.txt
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - tmp/
  - spec/
  - test/
  - docs/tmp/

breadcrumb_nav:
  enabled: true
  separator: "/"
  display_offline: true