title: Ecosystem
description: SIR Ecosystem Guides

url: "https://sir-lab.github.io"
baseurl: "/Ecosystem"

remote_theme: just-the-docs/just-the-docs@v0.5.2

plugins:
  - jekyll-remote-theme

search_enabled: false
heading_anchors: true

sass:
  sass_dir: assets/css
  style: compressed

back_to_top: true
back_to_top_text: "Back to top"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tmp/

breadcrumb_nav:
  enabled: true
  separator: "/"
  display_offline: true