title: Ecosystem
description: SIR Ecosystem Guides

# Urls
url: "https://sir-lab.github.io"
baseurl: "/Ecosystem"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.5.2
plugins:
  - jekyll-remote-theme

# Configurations
search_enabled: false
heading_anchors: true

aux_links: {}

# Back to top config
back_to_top: true
back_to_top_text: "Back to top"

# 告诉 Jekyll 忽略这些引起报错的主题说明文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tmp/               # 关键：忽略报错信息里提到的那个 tmp 文件夹


# 面包屑导航配置
breadcrumb_nav:
  enabled: true       # 确保已启用
  separator: "/"      # 分隔符，可以换成 ">"
  display_offline: true

# 强制显示所有层级 (关键项)
back_to_top: true
back_to_top_text: "Back to top"

# 如果主题版本支持，添加以下逻辑强制递归显示路径
# 有些版本的 just-the-docs 需要在对应页面的 Front Matter 里设置