title: Ecosystem
description: SIR Ecosystem Guides

# Urls
url: "https://sir-lab.github.io"
baseurl: "Ecosystem"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.5.2
plugins:
  - jekyll-remote-theme

# Configurations
search_enabled: true
heading_anchors: true

# Top right corner link
aux_links:
  "GitHub Repo":
    - "https://github.com/sir-lab/Ecosystem"

# Back to top config
back_to_top: true
back_to_top_text: "Back to top"
